
version: '3'

services:
  hr-worker:
    container_name: hr-worker
    build: ./hr-worker
    ports:
      - "8080:8080"
    networks:
      - monorepo-network

  ms-payroll:
    container_name: ms-payroll
    build: ./ms-payroll
    ports:
      - "8081:8081"
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge
